name: Laravel CD

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR ${{ secrets.AWS_REGION }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: '905418450006'
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Docker Login to ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ steps.login-ecr.outputs.registry }}

    # - name: Build Image
    #   uses: docker/build-push-action@v5
    #   id: build-image
    #   with:
    #     context: .
    #     provenance: false
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ github.sha }}
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    #     build-args: ''

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/905418450006.dkr.ecr.us-east-2.amazonaws.com/alegra:$IMAGE_TAG .
        docker push $ECR_REGISTRY/905418450006.dkr.ecr.us-east-2.amazonaws.com/alegra:$IMAGE_TAG

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull $ECR_REGISTRY/905418450006.dkr.ecr.us-east-2.amazonaws.com/alegra:$IMAGE_TAG
          docker stop tu-aplicacion || true
          docker rm tu-aplicacion || true
          docker run -d --name tu-aplicacion \
            -e DB_CONNECTION=${{ secrets.DB_CONNECTION }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            $ECR_REGISTRY/905418450006.dkr.ecr.us-east-2.amazonaws.com/alegra:$IMAGE_TAG

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USERNAME }}
    #     key: ${{ secrets.EC2_SSH_KEY }}
    #     script: |
    #       docker pull 905418450006.dkr.ecr.us-east-2.amazonaws.com/alegra:latest
    #       docker stop kitchen-service || true
    #       docker rm kitchen-service || true
    #       docker run -d --name kitchen-service 905418450006.dkr.ecr.us-east-2.amazonaws.com/alegra:latest
